<template>
  <div>
    <div id="simple_header" style="margin-top:30px">Overview</div>
    <div id="project_description" >
      <p>
        This page describes a prototype of Body Sensor Network (BSN) as a system to be autonomously 
        managed, namely a Self-Adaptive System. The BSN is an exemplar of a target system that 
        continuously monitors and analyzes the health of patients. It is composed of a set of 
        distributed sensors to collect vital signs of patients and transfer these signs to a central
        processor for analysis. In the basic configuration, the BSN is prone to a decay on its
        reliability due to failure in the software components. To cope with these flaws, the BSN
        is instrumented with a system manager that observes the reliability status and adapts the
        configurations towards maintaining the reliability desired level.
      </p>
      <p>
        We have implemented the BSN within the widely adopted Robot Operating System (ROS) for the
        sake of extensibility and maintainability. The designed ROS modules consist of five
        sensors and a central hub. The sensors are a thermometer [°C], an electrocardiograph [bpm],
        an oximeter [% SpO2/L of blood], a systolic arterial blood pressure [mmHg], and a diastolic 
        arterial blood pressure [mmHg]. Each vital sign is classified with respect to risk to the 
        patient health according to the table below. The central hub is responsible for fusing the
        vital signs and detecting whether the patient requires emergencial treatment, by means of 
        a variable patient risk which ranges from [0,100%] where 0% is no risk and 100% is the maximum risk. 
      </p>

      <div class="container3 ctr">
        <img src="../../assets/table.png" />
      </div>

      <br />

      <p>
        The remainder sections of this page: 1) explores the scenario in which the system is operating,
        2) briefly introduces the Goal-Oriented SAS design process used in the BSN development, and 
        3) details the step-by-step on how to experiment with the BSN.
      </p>

    </div>

    <div id="simple_header">Scenario under execution</div>
    <div id="project_description" >

      <p>
        The execution of the prototype accessible through this website simulates a scenario where multiple 
        sensors flood the central processor with a higher rate than what it can handle. Which might happen
        when there is a overflow of patients in the ICU using the BSN. On top of that, noise is generated by
        an external agent (Injector) triggers random failures on the sensors preventing them from forwarding 
        data to the central processor. The simulated failures reduce the number of messages received by the 
        central processor at a random factor, placing another layer of uncertainty on the system execution. 
        To cope with the disturbances into the reliability status, the system manager delivers reconfiguration
        signals containing increments/decrements to the sensors’ sampling rate that could give more or less 
        time for the central processor to maintain a always flowing processing queue.
      </p>

    </div>

    <div id="simple_header" style="margin-top:30px">Goal-Oriented SAS Design Process</div>
    <div id="project_description" >
      <!--The BSN is a multi process system implemented using C++ and ROS for 
      proccess communication.-->
      
      <div class="container3 ctr">
        <img id="img2" alt="bsn" class="img-responsive" src="../../assets/gm_architecture.png" />
      </div>
      <p style="font-size: 80%; text-align: center">Figure 1 - SAS design process for BSN</p>
      <br />
      <br />
      
      The end-to-end design of the BSN prototype is illustrated in Figure 1. From one side there 
      are the system requirements expressed in the representation of a contextual goal model. 
      From the other, an implementation view of the runtime self-adaptive system according to ROS 
      architecture. We followed the step-by-step briefly exposed in a 5 bullet list: 
      <br />(1) A Contextual Goal-Model (CGM) was specified based on elicited requirements; 
      <br /> (2) Then, a transformation from goal model to parametric formula was executed by 
      <a href="https://pistar-goda.herokuapp.com/">GODA-MDP</a>;
      <br /> (3) Accordingly to a mapping from goal model to software components, ros nodes were
       implemented to collaborate and satisfy the root goal; 
      <br /> (4) The prototype is configured and integrated to the system manager, the knowledge 
      repository and simulation nodes;
      <br />(5) Finally, the prototype is executed and the analyzed properties are exposed in this website.

      <!--The BSN itself is composed of five sensors: thermometer, eletrocardiograph, oximeter, systolic
      and diastolic pressure sensor. Each sensor is a ROS node which consumes data from pacient node, 
      filter and sends the data to central node, which fuse the data and calculate the patient's overall
      status. The patient node generates the data using 5x5 Markov chains. Generally, this model defines 
      probabilities of each state in order to maintain in its current position or migrating
      to different ones. Using Markov chains it is possible to create estates that represent normal 
      and abnormal health conditions. That enables profile generation as in order to simulate a healthy 
      patient it is simply needed to maintain his sensors in normal condition states (healthy ones). 
      Thus, there where defined 5 state in the data generating chain: high risk state with data below and 
      above expected, medium risk state with data below and above expected and low risk state with data accordingly 
      to expected. -->
    </div>

    <div id="simple_header">How to experiment with the BSN</div>
    <div id="project_description" >
      <p>
        In this section, we further explore the basic steps by which one can setup and execute the BSN. 
        Our goal with this section is to provide means of evaluating, testing and comparing adaptation
        engines and algorithms in the healthcare domain. 
      </p>

      <p>  
        Aided by the ROSLaunch feature, the configuration and execution of each module is done using a XML
        with .launch extension. These files contains parameters that can be read and mapped to variables
        in the set up method of each ros component. They can be found in the configuration folder from the
        project.
        --All roslaunch files are in the configuration folder and the parameters 
        can be modified as required.-->
      </p>

      <p>
        Follow the step-by-step to configure and launch the BSN:
      </p>

      <h4 id="step-1-getting-bsn">Step 1: Clone the BSN code from git</h4>
      <p>
      The BSN <a href="https://github.com/lesunb/bsn" title="BSN repository">repository</a> contains 
      the source code and the installation tutorial.
      </p>

      <h4 id="step-2-data-collection-setup">Step 2: Vital Signs Generation Setup</h4>
      <p>
      The vital signs generation is configured in the file: configuration/environment/patient.launch. 
      Each vital sign is modeled by a markov chain where the states represent the risk level that
      the data represents to the patient, from Table 1, and each transition represents the probability
      from decaying or improving the vital sign risk. Thus, the configuration stands for defining the 
      range of data that represents the state and the probabilities from the transitions. From a transition
      matrix perspective. As a result, distinct patient profiles can be simulated, since the heart rate of 
      85bpm could be of no risk to some humans but to others it is of high risk.
      </p>
      <p>
      In the example below, we set up the patient module to generate heart rate data, the frequency to perform 
      a transition from states, the transition matrix and a offset, the time it will take to begin the state changing.
      </p>
      
      <span><pre><code>
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"vitalSigns"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"heart_rate"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_Change"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"0.2"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_Offset"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"10"</span>/&gt;

        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_State0"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"72,21,4,2,1"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_State1"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"14,61,19,4,2"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_State2"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"1,17,60,20,2"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_State3"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"0,2,15,70,13"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_State4"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"0,0,2,20,77"</span>/&gt;

        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_HighRisk0"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"0,70"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_MidRisk0"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"70,85"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_LowRisk"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"85,97"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_MidRisk1"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"97,115"</span>/&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"heart_rate_HighRisk1"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"115,300"</span>/&gt;
      </code></pre></span>
    
      <h4 id="step-3-setting-up-the-sensors">Step 3: Sensor's setup</h4>
      <p>
        The sensors are configured in the files: configurations/target_system/g3_tx.launch. It is 
        important to observe that the names of the modules follow the goal model to ros component
        mapping previously mentioned. Each sensor should be configured to evaluate the data collected 
        with the values for low, medium and high risks. Last but not least, initial frequency of
        each sensor can be chosen. 
      </p>

      <span><pre><code>
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"frequency"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"1"</span> /&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"lowrisk"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"0,20"</span> /&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"midrisk"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"21,65"</span> /&gt;
        &lt;<span class="hljs-built_in">param</span> name=<span class="hljs-string">"highrisk"</span> <span class="hljs-built_in">value</span>=<span class="hljs-string">"66,100"</span> /&gt;
      </code></pre></span>

      <h4 id="step-4-building-the-manager-system">Step 4: Building the System Manager</h4>
      
      <p>
        The system manager is responsible for the target system adaptation. Following from our goal-oriented
        design process the system manager it employs the parametric formula for analyzing the current reliability
        and cost status' and reason on how to adapt the BSN configurations towards maintaining the desired level
        of the properties. Whereas in the current version of the system manager, we applied a hybrid approach
        that unites control theory and AI for optimizing the system's reliaiblity. The current values can be 
        obtained from querying the Knowledge repository for the data. We exemplify the request of the reliability 
        of each sensor and centralhub in respect to the number of failures in a window of execution.</p>
      
      <span><pre><code>
        <span class="hljs-symbol">archlib:</span>:DataAccessRequest c_srv<span class="hljs-comment">;</span>
        c_srv.request.name = ros::this_node::getName()<span class="hljs-comment">;</span>
        c_srv.request.query = <span class="hljs-string">"all:reliability"</span><span class="hljs-comment">;</span>
        client_module.call(c_srv)<span class="hljs-comment">;</span>
      </code></pre></span>
      
      <p>
        To send an adaptation command, the manager must publish a message to the topic &quot;log_adapt&quot;, 
        as exemplified below, where the g3t1_1 sensor (oximeter) is adapted changing it&#39;s frequency.</p>
      
      <span><pre><code>
        <span class="hljs-symbol">archlib:</span>:AdaptationCommand msg<span class="hljs-comment">;</span>
        msg.source = ros::this_node::getName()<span class="hljs-comment">;</span>
        msg.target = <span class="hljs-string">"g3t1_1"</span><span class="hljs-comment">;</span>
        msg.action = <span class="hljs-string">"freq=1.24"</span><span class="hljs-comment">;</span>
        adapt.publish(msg)<span class="hljs-comment">;</span>
      </code></pre></span>


      <h4 id="step-5-run">Step 5: Execute the BSN on your machine</h4>
      <p>
        There is a run.sh file on the project's root folder. Run it with 
        <span style="color: purple;">bash run.sh</span> in the command line.
      </p>

    </div>



    <div id="us_section">
      <div style="font-size: 150%; margin-left: 60px;">Our development team</div>
      <div id="credentials">
        Dr. Genaína Nunes Rodrigues - Project Leader and Associate Professor at UnB
        <br />Ricardo Diniz Caldas - PhD student at Chalmers
        <br />
        <br />Gabriel Levi Gomes - Undergrad Computer Science student at UnB
        <br />
        <br />Léo Moraes da Silva - Undergrad Computer Science student at UnB
      </div>
      <div id="credentials">
        <a target="_blank" rel="noopener noreferrer" href="https://cic.unb.br/~genaina/">Page</a>
        <br />
        <br />
        <a target="_blank" rel="noopener noreferrer" href="https://github.com/rdinizcal">Github</a>
        <br />
        <br />
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://github.com/gabrielevi10"
        >Github</a>
        <br />
        <br />
        <a target="_blank" rel="noopener noreferrer" href="https://github.com/leooleo">Github</a>
        <br />
        <br />
        <br />
        <br />
      </div>
    </div>    
  </div>
</template>

<style scoped>
#select_wrapper {
  margin-left: 20vw;
}
#head {
  text-align: center;
  background-color: #478dff;
  color: white;
  height: 60vh;
  margin-bottom: 50px;
}
#simple_header {
  text-align: center;
  border-bottom: 6px solid #478dff;
  width: 50%;
  margin-left: 25%;
  font-weight: 800;
  font-size: 270%;
}
#project_description {
  margin-top: 50px;
  margin-bottom: 50px;
  margin-left: 20%;
  margin-right: 20%;
  text-align: justify;
  font-size: 130%;
  color: #515151;
}

#us_section {
  width: 100vw;
  font-size: 200%;
  color: white;
  background-color: #003d72;
  height: auto;
  float: left;
}

#credentials {
  margin-top: 50px;
  color: white;
  margin-left: 60px;
  font-size: 55%;

  float: left;
}

#img2 {
  width: 1100px;
  height: auto;
}

.ctr {
  display: flex;
  flex-direction: column;
  justify-content: center;  /* Centering y-axis */
  align-items :center; /* Centering x-axis */
}

</style>
